this._=this._||{};(function(_){var window=this;
try{
var da,ha,ja,ea,na,oa,ra,ta,va,ya,Ka,La;_.q=function(a){return function(){return _.aa[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.aa=[];da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global?window.global:this;ha=function(){da.Symbol||(da.Symbol=ea);ha=function(){}};ja=0;ea=function(a){return"jscomp_symbol_"+a+ja++};na=function(){ha();da.Symbol.iterator||(da.Symbol.iterator=da.Symbol("iterator"));na=function(){}};
oa=function(a,b){na();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};ha();na();d[window.Symbol.iterator]=function(){return d};return d};ra=function(a,b){!Array.prototype[a]&&Object.defineProperties&&Object.defineProperty&&Object.defineProperty(Array.prototype,a,{configurable:!0,enumerable:!1,writable:!0,value:b})};
ta=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};va=function(a){var b=ta(this,null,"repeat");if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};
ya=function(a,b){var c=ta(this,a,"startsWith");a+="";for(var d=c.length,e=a.length,f=Math.max(0,Math.min(b|0,c.length)),g=0;g<e&&f<d;)if(c[f++]!=a[g++])return!1;return g>=e};String.prototype.startsWith||(String.prototype.startsWith=ya);ra("entries",function(){return oa(this,function(a,b){return[a,b]})});ra("keys",function(){return oa(this,function(a){return a})});ra("values",function(){return oa(this,function(a,b){return b})});String.prototype.repeat||(String.prototype.repeat=va);_.Ba=_.Ba||{};
_.r=this;_.Da=function(a){return void 0!==a};_.Ea=function(){};
_.Fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.Ha=function(a){return"array"==_.Fa(a)};_.t=function(a){return"string"==typeof a};_.Ia="closure_uid_"+(1E9*Math.random()>>>0);Ka=function(a,b,c){return a.call.apply(a.bind,arguments)};
La=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){_.u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Ka:La;return _.u.apply(null,arguments)};
_.Na=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Qa=Date.now||function(){return+new Date};_.A=function(a,b){var c=a.split("."),d=_.r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.Da(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};
_.B=function(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fw=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
_.Sa=function(a,b){return b};_.D=function(a,b){b=_.Sa(a,b);_.A(a,b)};_.Ta=window.gadgets||{};_.Ua=window.osapi=window.osapi||{};_.google=window.google||{};window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});
_.Wa=window;_.Xa=window.document;_.Ya=_.Wa.location;_.Za=/\[native code\]/;_.$a=function(a,b,c){return a[b]=a[b]||c};_.ab=function(){var a;if((a=Object.create)&&_.Za.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.bb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.db=function(a,b){if(!a)throw Error(b||"");};_.eb=_.$a(_.Wa,"gapi",{});
_.fb=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.ib=function(a,b,c){_.gb(a,b,c,"add","at")};_.gb=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.jb=_.$a(_.Wa,"___jsl",_.ab());_.$a(_.jb,"I",0);_.$a(_.jb,"hel",10);var kb,nb,ob,qb,rb,sb;kb=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};nb=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};ob=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};qb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!ob(a[c])&&!ob(b[c])?qb(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=ob(b[c])?[]:{},qb(a[c],b[c])):a[c]=b[c])};
rb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
sb=function(a){nb(!0);var b=window.___gcfg,c=kb("cu");if(b&&b!==window.___gu){var d={};qb(d,b);c.push(d);window.___gu=b}var b=kb("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,kb("us"));for(var g=0;g<e.length;++g)for(var k=e[g],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(g=f.nodeType,f=3==g||4==g?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=rb(f))&&b.push(f));a&&(d={},qb(d,a),c.push(d));d=kb("cd");a=0;for(b=d.length;a<b;++a)qb(nb(),d[a]);d=kb("ci");a=0;for(b=d.length;a<b;++a)qb(nb(),d[a]);a=0;for(b=c.length;a<b;++a)qb(nb(),c[a])};_.F=function(a,b){if(!a)return nb();for(var c=a.split("/"),d=nb(),e=0,f=c.length;d&&"object"===typeof d&&e<f;++e)d=d[c[e]];return e===c.length&&void 0!==d?d:b}; _.tb=function(a,b){var c=a;if("string"===typeof a){for(var d=c={},e=a.split("/"),f=0,g=e.length;f<g-1;++f)var k={},d=d[e[f]]=k;d[e[f]]=b}sb(c)};
var ub=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.$a(_.jb,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};ub&&ub();sb();_.D("gapi.config.get",_.F);_.D("gapi.config.update",_.tb);
}catch(e){_._DumpException(e)}
try{
var Bb,Cb,Eb,Fb,Hb,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Rb,Tb,Vb;_.xb=function(a){return!!a&&"object"===typeof a&&_.Za.test(a.push)};_.yb=function(a,b,c){if(a){_.db(_.xb(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};_.Ab=function(a,b,c){if(a)if(_.xb(a))_.yb(a,b,c);else{_.db("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)_.bb(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};
Bb=function(a){a=a.sort();for(var b=[],c=void 0,d=0;d<a.length;d++){var e=a[d];e!=c&&b.push(e);c=e}return b};Cb=function(){var a=[],b=_.jb.H;b&&_.Ab(b,function(b){a.push.apply(a,b.L)});return Bb(a)};_.Db=function(a){if(_.Za.test(Object.keys))return Object.keys(a);var b=[],c;for(c in a)_.bb(a,c)&&b.push(c);return b};Lb={};Mb=0;Nb=_.ab();Ob=_.ab();Pb=function(a){return"number"===typeof a&&a>Math.random()};
_.Qb=function(a){if("undefined"===typeof Eb){var b=_.F("report")||{},c=b.rate;Jb=b.timeout||1E3;Fb=b.host||"https://plus.google.com";Hb=b.path||"/_/widget/report";Eb=[];Pb(c)&&(Eb=b.apis||[]);var b=b.apiRate||{},d;for(d in b)Pb(b[d])&&Eb.push(d)}for(d=0;d<Eb.length;++d)if((new RegExp("^"+Eb[d]+"$")).test(a))return!0;return!1};Rb=function(a){delete Lb[a]};
Tb=function(){Kb&&(_.Wa.clearTimeout(Kb),Kb=0);Kb=_.Wa.setTimeout(function(){var a;a=window.document.location;a=a.protocol+"//"+a.host+a.pathname;var b=_.Db(Ob).join(":");a=[Fb,Hb,"?api=",(0,window.encodeURIComponent)(b),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(Cb().join(":"))].join("");Ob=_.ab();var b=new window.Image,c=Mb++;Lb[c]=b;b.onload=b.onerror=_.Na(Rb,c);b.src=a;Kb=0},Jb)};_.Ub=function(a){Nb[a]||(Ob[a]=!0,Nb[a]=!0,Tb())};Vb=_.Sa; _.Sa=function(a,b){var c=Vb(a,b);"function"===typeof b&&_.Qb(a)&&(c=function(c){_.Ub(a);return b.apply(this,arguments)});return c};

}catch(e){_._DumpException(e)}
try{
_.Aj=window.gapi&&window.gapi.util||{};
}catch(e){_._DumpException(e)}
try{
var Cj=_.Aj=_.Aj||{};window.___jsl=window.___jsl||{};Cj.kq={R:function(){return window.___jsl.bsh},Kx:function(){return window.___jsl.h},Ot:function(a){window.___jsl.bsh=a},bN:function(a){window.___jsl.h=a}};
}catch(e){_._DumpException(e)}
try{
var Fj,Gj;Fj=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/u\/(\d)\//;Gj=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/b\/(\d{10,})\//;_.Hj=function(a){var b=_.F("googleapis.config/sessionIndex");null==b&&(b=window.__X_GOOG_AUTHUSER);if(null==b){var c=window.google;c&&(b=c.authuser)}null==b&&(a=a||window.location.href,b=_.fb(a,"authuser")||null,null==b&&(b=(b=a.match(Fj))?b[1]:null));return null==b?null:String(b)};
_.Ij=function(a){var b=_.F("googleapis.config/sessionDelegate");null==b&&(b=(a=(a||window.location.href).match(Gj))?a[1]:null);return null==b?null:String(b)};_.Jj=function(a,b){var c=_.Hj(a)||b,d=_.Ij(a),e="";c&&(e+="u/"+c+"/");d&&(e+="b/"+d+"/");return e||null};

}catch(e){_._DumpException(e)}
try{
_.Kj=function(a){var b;if(b=_.F("enableMultilogin"))if(b=a("cookie_policy"))b=String(a("immediate")||""),a=String(a("prompt")||""),b=!("true"===b.toLowerCase()||"none"===a.toLowerCase());return b?!0:!1};
_.Lj=function(a,b,c){a=String(a);if(null!=(_.fb(a,"authuser")||null)||null!=(_.fb(a,"hd")||null))return a;b=_.Hj(b);if(c){var d=a,e=d.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(e&&e[0]){var f=e[1],g=e[4],k=e[5];e[3]=="/"+c&&(d=(f||"")+(g||"/")+(k||""))}if((e=d.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&e[0]){var f=e[2],l=e[4]||e[5],k=e[6];null!=b&&(d=(f||"")+"/"+c+"/"+(0,window.encodeURIComponent)(b)+(l||"/")+(k||""));return d}}null==
b?_.Kj(function(b){return _.fb(a,b)||null})||(l=(0,window.encodeURIComponent)("authuser")+"=0"):l=b.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)(String(b)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(b)].join(""):["authuser=",(0,window.encodeURIComponent)(b)].join("");c=a.split("#");b=c[0].indexOf("?");0>b?c[0]=[c[0],"?",l].join(""):(d=[c[0]],b<c[0].length-1&&d.push("&"),d.push(l),c[0]=d.join("")); return d=c.join("#")};_.google.MX=_.Lj;_.google.Ir=_.Hj;_.google.hX=_.Ij;_.google.iX=_.Jj;

}catch(e){_._DumpException(e)}
try{
var Mj=function(){this.S=-1};var Nj=function(){this.S=64;this.R=[];this.V=[];this.ra=[];this.U=[];this.U[0]=128;for(var a=1;a<this.S;++a)this.U[a]=0;this.W=this.T=0;this.reset()};_.B(Nj,Mj);Nj.prototype.reset=function(){this.R[0]=1732584193;this.R[1]=4023233417;this.R[2]=2562383102;this.R[3]=271733878;this.R[4]=3285377520;this.W=this.T=0};
var Oj=function(a,b,c){c||(c=0);var d=a.ra;if(_.t(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.R[0];c=a.R[1];for(var g=a.R[2],k=a.R[3],l=a.R[4],m,e=0;80>e;e++)40>e?20>e?(f=k^c&(g^k),m=1518500249):(f=c^g^k,m=1859775393):60>e?(f=c&g|k&(c|g),m=2400959708):(f=c^g^k,m=3395469782),
f=(b<<5|b>>>27)+f+l+m+d[e]&4294967295,l=k,k=g,g=(c<<30|c>>>2)&4294967295,c=b,b=f;a.R[0]=a.R[0]+b&4294967295;a.R[1]=a.R[1]+c&4294967295;a.R[2]=a.R[2]+g&4294967295;a.R[3]=a.R[3]+k&4294967295;a.R[4]=a.R[4]+l&4294967295};
Nj.prototype.update=function(a,b){if(null!=a){_.Da(b)||(b=a.length);for(var c=b-this.S,d=0,e=this.V,f=this.T;d<b;){if(0==f)for(;d<=c;)Oj(this,a,d),d+=this.S;if(_.t(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.S){Oj(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.S){Oj(this,e);f=0;break}}this.T=f;this.W+=b}};
Nj.prototype.digest=function(){var a=[],b=8*this.W;56>this.T?this.update(this.U,56-this.T):this.update(this.U,this.S-(this.T-56));for(var c=this.S-1;56<=c;c--)this.V[c]=b&255,b/=256;Oj(this,this.V);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.R[c]>>d&255,++b;return a};
_.Pj=function(){this.Ij=new Nj};_.h=_.Pj.prototype;_.h.reset=function(){this.Ij.reset()};_.h.pC=function(a){this.Ij.update(a)};_.h.dx=function(){return this.Ij.digest()};_.h.Du=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.pC(b)};_.h.If=function(){for(var a=this.dx(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

}catch(e){_._DumpException(e)}
try{
_.Yl=function(a,b){a=a||{};for(var c in a)_.bb(a,c)&&(b[c]=a[c])};
}catch(e){_._DumpException(e)}
try{
var $l,Zl,fm,gm,am,dm,bm,hm,cm,Zl;_.em=function(){var a;Zl?(a=new _.Wa.Uint32Array(1),$l.getRandomValues(a),a=Number("0."+a[0])):(a=am,a+=(0,window.parseInt)(bm.substr(0,20),16),bm=cm(bm),a/=dm+Math.pow(16,20));return a};$l=_.Wa.crypto;Zl=!1;fm=0;gm=0;am=1;dm=0;bm="";hm=function(a){a=a||_.Wa.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;am=am*b%dm;0<fm&&++gm==fm&&_.gb(_.Wa,"mousemove",hm,"remove","de")};cm=function(a){var b=new _.Pj;b.Du(a);return b.If()};
Zl=!!$l&&"function"==typeof $l.getRandomValues;Zl||(dm=1E6*(window.screen.width*window.screen.width+window.screen.height),bm=cm(_.Xa.cookie+"|"+_.Xa.location+"|"+(new Date).getTime()+"|"+Math.random()),fm=_.F("random/maxObserveMousemove")||0,0!=fm&&_.ib(_.Wa,"mousemove",hm));

}catch(e){_._DumpException(e)}
try{
var im,km,lm,mm,nm,om,pm,qm,rm,sm,vm,wm,xm,ym,zm,Am;im=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.jm=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;km=function(a,b){var c=[];if(a)for(var d in a)if(_.bb(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};lm=function(a){return a.Fw+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.pn.length?"#"+a.pn.join("&"):"")};
mm=function(a){a=a.match(im);var b=_.ab();b.Fw=a[1];b.query=a[3]?[a[3]]:[];b.pn=a[5]?[a[5]]:[];return b};nm=/'/g;om=/"/g;pm=/>/g;qm=/</g;rm=/&/g;sm=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.tm=function(a,b){var c="";2E3<b.length&&(c=b.substring(2E3),b=b.substring(0,2E3));var d=a.createElement("div"),e=a.createElement("a");e.href=b;d.appendChild(e);d.innerHTML=d.innerHTML;b=String(d.firstChild.href);d.parentNode&&d.parentNode.removeChild(d);return b+c};
_.um=function(a,b,c,d){a=mm(a);a.query.push.apply(a.query,km(b,d));a.pn.push.apply(a.pn,km(c,d));return lm(a)};vm=function(a){return String(a).replace(rm,"&amp;").replace(qm,"&lt;").replace(pm,"&gt;").replace(om,"&quot;").replace(nm,"&#39;")};xm=function(){var a=_.jb.onl;if(!a){a=_.ab();_.jb.onl=a;var b=_.ab();a.e=function(a){var d=b[a];d&&(delete b[a],d())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a}; ym=function(a,b){var c=b.onload;return"function"===typeof c?(xm().a(a,c),c):null};zm=function(a){_.db(/^\w+$/.test(a),"Unsupported id - "+a);xm();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};Am=function(a){xm().r(a)};
var Cm,Dm,Hm;_.Bm={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};Cm={allowtransparency:!0,onload:!0};Dm=0;_.Em=function(a,b){var c,d=0;do c=b.id||["I",Dm++,"_",(new Date).getTime()].join("");while(a.getElementById(c)&&5>++d);_.db(5>d,"Error creating iframe id");return c};_.Fm=function(a,b){return a?b+"/"+a:""};
_.Gm=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);_.Yl(d.queryParams||{},e);_.Yl(d.fragmentParams||{},f);var g=d.connectWithQueryParams?e:f,k=d.pfname,l=_.ab();l.id=c;l.parent=a.location.protocol+"//"+a.location.host;c=_.fb(a.location.href,"parent");k=k||"";!k&&c&&(k=_.Fm(_.fb(a.location.href,"id",""),_.fb(a.location.href,"pfname","")));l.pfname=k;_.Yl(l,g);(l=_.fb(b,"rpctoken")||e.rpctoken||f.rpctoken)||(l=g.rpctoken=d.rpctoken||String(Math.round(1E8*
_.em())));d.rpctoken=l;g=a.location.href;a=_.ab();(l=_.fb(g,"_bsh",_.jb.bsh))&&(a._bsh=l);(g=_.jb.dpo?_.jb.h:_.fb(g,"jsh",_.jb.h))&&(a.jsh=g);d.hintInFragment?_.Yl(a,f):_.Yl(a,e);return _.um(b,e,f,d.paramsSerializer)};Hm=function(a){_.db(!a||_.jm.test(a),"Illegal url for new iframe - "+a)};
_.Im=function(a,b,c,d,e){Hm(c.src);var f,g=ym(d,c),k=g?zm(d):"";try{window.document.all&&(f=a.createElement('<iframe frameborder="'+vm(String(c.frameborder))+'" scrolling="'+vm(String(c.scrolling))+'" '+k+' name="'+vm(String(c.name))+'"/>'))}catch(m){}finally{f||(f=a.createElement("iframe"),g&&(f.onload=function(){f.onload=null;g.call(this)},Am(d)))}for(var l in c)a=c[l],"style"===l&&"object"===typeof a?_.Yl(a,f.style):Cm[l]||f.setAttribute(l,String(a));(l=e&&e.beforeNode||null)||e&&e.dontclear|| sm(b);b.insertBefore(f,l);f=l?l.previousSibling:b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var Jm,Mm;Jm=/^:[\w]+$/;_.Km=/:([a-zA-Z_]+):/g;_.Lm=function(){var a=_.Hj()||"0",b=_.Ij(),c=_.Jj(void 0,a),d=!1===_.F("isLoggedIn"),e=d?"_/im/":"";e&&(c="");var f=_.F("iframes/:socialhost:"),g=_.F("iframes/:im_socialhost:");return wm={socialhost:f,ctx_socialhost:d?g:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};Mm=function(a,b){return _.Lm()[b]||""};_.Nm=function(a){return _.tm(_.Xa,a.replace(_.Km,Mm))};
_.Om=function(a){var b=a;Jm.test(a)&&(b=_.F("iframes/"+b.substring(1)+"/url"),_.db(!!b,"Unknown iframe url config for - "+a));return _.Nm(b)};
_.Pm=function(a,b,c){var d=c||{};c=d.attributes||{};_.db(!d.allowPost||!c.onload,"onload is not supported by post iframe");a=_.Om(a);c=b.ownerDocument||_.Xa;var e=_.Em(c,d);a=_.Gm(c,a,e,d);var f=_.ab();_.Yl(_.Bm,f);_.Yl(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;if((d||{}).allowPost&&2E3<a.length){var g=mm(a);f.src="";f["data-postorigin"]=a;a=_.Im(c,b,f,e);var k;if(-1!=window.navigator.userAgent.indexOf("WebKit")){k=a.contentWindow.document;k.open();var f=k.createElement("div"),l={},m=e+"_inner";
l.name=m;l.src="";l.style="display:none";_.Im(c,f,l,m,d)}f=(d=g.query[0])?d.split("&"):[];d=[];for(l=0;l<f.length;l++)m=f[l].split("=",2),d.push([(0,window.decodeURIComponent)(m[0]),(0,window.decodeURIComponent)(m[1])]);g.query=[];f=lm(g);_.db(_.jm.test(f),"Invalid URL: "+f);g=c.createElement("form");g.action=f;g.method="POST";g.target=e;g.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type="hidden",f.name=d[e][0],f.value=d[e][1],g.appendChild(f);b.appendChild(g);g.submit(); g.parentNode.removeChild(g);k&&k.close();b=a}else b=_.Im(c,b,f,e,d);return b};

}catch(e){_._DumpException(e)}
try{
_.Dj=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e|| "https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c};

}catch(e){_._DumpException(e)}
try{
_.Aj.rb=function(a){return _.Dj(a)};
}catch(e){_._DumpException(e)}
try{
_.J=_.J||{};
}catch(e){_._DumpException(e)}
try{
_.J=_.J||{};_.J.Ao=function(a,b,c){for(var d=[],e=2,f=arguments.length;e<f;++e)d.push(arguments[e]);return function(){for(var c=d.slice(),e=0,f=arguments.length;e<f;++e)c.push(arguments[e]);return b.apply(a,c)}};_.J.Il=function(a){var b,c,d={};for(b=0;c=a[b];++b)d[c]=c;return d};

}catch(e){_._DumpException(e)}
try{
_.J=_.J||{};
(function(){function a(a,b){return String.fromCharCode(b)}var b={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.J.escape=function(a,b){if(a){if("string"===typeof a)return _.J.fn(a);if("Array"===typeof a)for(var e=0,f=a.length;e<f;++e)a[e]=_.J.escape(a[e]);else if("object"===typeof a&&b){e={};for(f in a)a.hasOwnProperty(f)&&(e[_.J.fn(f)]=_.J.escape(a[f],!0));return e}}return a};_.J.fn=function(a){if(!a)return a;for(var d=[],e,f,g=0,k= a.length;g<k;++g)e=a.charCodeAt(g),f=b[e],!0===f?d.push("&#",e,";"):!1!==f&&d.push(a.charAt(g));return d.join("")};_.J.pY=function(b){return b?b.replace(/&#([0-9]+);/g,a):b}})();

}catch(e){_._DumpException(e)}
try{
_.Xl=_.Xl||{};_.Xl.rI=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

}catch(e){_._DumpException(e)}
try{
_.Xl=_.Xl||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.Xl.Mc=function(){var b=_.Xl.rI().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift(),d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight)var g=f.offsetTop+f.offsetHeight+a(f,"margin-bottom"),b=Math.max(b,g);c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

}catch(e){_._DumpException(e)}
try{
_.$b=function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(g){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Yb=function(b){a(2,b)};_.Wb=function(b){a(3,b)};_.Zb=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b}();

}catch(e){_._DumpException(e)}
try{
_.J=_.J||{};(function(){var a=[];_.J.QX=function(b){a.push(b)};_.J.cY=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
}catch(e){_._DumpException(e)}
try{
_.ac=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.bc=function(a,b){var c=_.$a(_.jb,"watt",_.ab());_.$a(c,a,b)};_.J=_.J||{};
(function(){var a=null;_.J.mc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,g=b.length;f<g;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.J.mc()})();
_.D("gadgets.util.getUrlParameters",_.J.mc);
}catch(e){_._DumpException(e)}
try{
_.cc=window.console;_.dc=function(a){_.cc&&_.cc.log&&_.cc.log(a)};_.ec=function(){};
}catch(e){_._DumpException(e)}
try{
_.fc=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.tb(a());return{register:function(a,c,d){d&&d(_.F())},get:function(a){return _.F(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.tb(a)},jc:function(){}}}();
_.D("gadgets.config.register",_.fc.register);_.D("gadgets.config.get",_.fc.get);_.D("gadgets.config.init",_.fc.jc);_.D("gadgets.config.update",_.fc.update);
}catch(e){_._DumpException(e)}
try{
var gc=function(a){return 10>a?"0"+a:a},hc={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},ic=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=hc[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";
b=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(ic(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.bb(a,c)&&"string"===typeof c&&(d=ic(a[c]))&&b.push(ic(c)+":"+d);return"{"+b.join(",")+"}"}return""}},jc=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+
a+")")}catch(b){}return!1},kc=!1,lc;try{kc=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(a){}lc=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.mc=kc?window.JSON.stringify:ic;_.nc=kc?lc:jc;lc||(Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",gc(this.getUTCMonth()+1),"-",gc(this.getUTCDate()),"T",gc(this.getUTCHours()),":",gc(this.getUTCMinutes()),":",gc(this.getUTCSeconds()),"Z"].join("")});

}catch(e){_._DumpException(e)}
try{
_.D("gadgets.json.stringify",_.mc);_.D("gadgets.json.parse",_.nc);_.fb(_.Wa.location.href,"rpctoken")&&_.ib(_.Xa,"unload",function(){});
}catch(e){_._DumpException(e)}
try{
var oc,rc;oc=function(){var a=_.Xa.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.pc=function(a){if(oc())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Wa.addEventListener?(_.Wa.addEventListener("load",c,!1),_.Wa.addEventListener("DOMContentLoaded",c,!1)):_.Wa.attachEvent&&(_.Wa.attachEvent("onreadystatechange",function(){oc()&&c.apply(this,arguments)}),_.Wa.attachEvent("onload",c))}};_.qc=function(a,b){if(!oc())try{a()}catch(c){}_.pc(b)}; rc=rc||{};rc.ZA=null;rc.Oz=null;rc.Vn=null;rc.frameElement=null;
rc=rc||{};
rc.Ou||(rc.Ou=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.nc)(a.data);if(b&&b.f){(0,_.Zb)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.K.Wg(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Wb("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{cj:function(){return"wpm"},R:function(){return!0},jc:function(f,g){_.fc.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=g;a(b);d("..",!0);return!0},xc:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.K.Wg(a),e=_.K.qw(a);d?window.setTimeout(function(){var a=(0,_.mc)(c);(0,_.Zb)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Wb("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
rc=rc||{};
rc.nn||(rc.nn=function(){function a(a,b){H[b]=H[b]||function(){a.apply({},arguments)}}function b(){if(null===v&&window.document.body&&l){var a=l+"?cb="+Math.random()+"&origin="+G+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="___xpcswf" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;v=c.firstChild}++x;null!==w&&(null!==v||50<=x)?window.clearTimeout(w):w=window.setTimeout(b,100)}function c(){E[".."]||(k(".."),z++,50<=z&&null!==C?(window.clearTimeout(C),C=null):C=window.setTimeout(c,100))}function d(){if(null!==v&&v.setup)for(;0<y.length;){var a=y.shift(),b=a.EN;v.setup(a.Kj,".."===b?_.K.Op:b,".."===b?"INNER":"OUTER")}null!==w&&window.clearTimeout(w);w=null}function e(){E[".."]||null!==
C||(C=window.setTimeout(c,100))}function f(a,b,c){b=_.K.Wg(a);var d=_.K.Rg(a);v["sendMessage_"+(".."===a?_.K.Op:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(v,(0,_.mc)(c),b);return!0}function g(a,b){var c=(0,_.nc)(a),d=c._scr;d?(p(d,!0),E[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){n(c,b)},0)}function k(a,b){var c=_.K.Op,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l=null,m=!1,n=null,p=null,v=null,y=[],w=null,x=0,z=0,C=null,E={},G=window.location.protocol+"//"+window.location.host,H;window.___jsl=
window.___jsl||{};H=window.___jsl._fm={};_.fc.register("rpc",null,function(a){m&&(l=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(g,"receiveMessage");return{cj:function(){return"flash"},R:function(){return!0},jc:function(a,b){n=a;p=b;return m=!0},xc:function(a,c){y.push({Kj:c,EN:a});null===v&&null===w&&(w=window.setTimeout(b,100));return!0},call:f,KF:g,S:d,T:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.K&&_.K||(_.K=window.gadgets.rpc,_.K.config=_.K.config,_.K.register=_.K.register,_.K.unregister=_.K.unregister,_.K.NA=_.K.registerDefault,_.K.oC=_.K.unregisterDefault,_.K.rx=_.K.forceParentVerifiable,_.K.call=_.K.call,_.K.Wk=_.K.getRelayUrl,_.K.Zf=_.K.setRelayUrl,_.K.Wo=_.K.setAuthToken,_.K.Rl=_.K.setupReceiver,_.K.Rg=_.K.getAuthToken,_.K.Bt=_.K.removeReceiver,_.K.Vx=_.K.getRelayChannel,_.K.Po=_.K.receive,_.K.KA=_.K.receiveSameDomain,_.K.rb=
_.K.getOrigin,_.K.Wg=_.K.getTargetOrigin,_.K.qw=_.K._getTargetWin,_.K.JF=_.K._parseSiblingId);else{_.K=function(){function a(a,b){if(!ma[a]){var c=Aa;b||(c=Ma);ma[a]=c;for(var d=fa[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=E[a];c.call(a,f.f,f)}fa[a]=[]}}function b(){function a(){ba=!0}X||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),X=!0)}function c(a,c,d,e,f){E[c]&&E[c]===d||(_.Wb("Invalid gadgets.rpc token. "+
E[c]+" vs "+d),Ja(c,2));f.onunload=function(){I[c]&&!ba&&(Ja(c,1),_.K.Bt(c))};b();e=(0,_.nc)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(E[b.f]&&E[b.f]!==b.t&&(_.Wb("Invalid gadgets.rpc token. "+E[b.f]+" vs "+b.t),Ja(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.K.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,g;try{g=e(f)}catch(k){}f&&
g==d||(f=c);b.referer=f}d=(x[b.s]||x[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.K.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function g(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==I[a]){"undefined"===typeof I[a]&&(I[a]=0);var c=g(a);".."!==a&&null==c||!0!==Aa.xc(a,b)?!0!==I[a]&&10>I[a]++?window.setTimeout(function(){k(a,b)},500):(ma[a]=Ma,I[a]=!0):I[a]=!0}}function l(a){(a=z[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));z[a]=b;"undefined"!==typeof c&&(C[a]=!!c)}function n(a,b){b=b||"";E[a]=String(b);k(a,b)}function p(a){a=(a.passReferrer||"").split(":",2);Pa=a[0]||"none";ca=a[1]||"origin"}function v(b){"true"===String(b.useLegacyProtocol)&&(Aa=rc.Vn||Ma,Aa.jc(d,a))}function y(a,b){function c(d){d=d&&d.rpc||{};p(d);var f=d.parentRelayUrl||"",f=e(W.parent||b)+f;m("..",f,"true"===String(d.useLegacyProtocol));
v(d);n("..",a)}!W.parent&&b?c({}):_.fc.register("rpc",null,c)}function w(a,b,c){if(".."===a)y(c||W.rpctoken||W.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.J)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.K.rb(d);m(a,b);b=_.J.mc(d);n(a,c||b.rpctoken)}}var x={},z={},C={},E={},G=0,H={},I={},W={},ma={},fa={},Pa=null,ca=null,Y=window.top!==window.self,xa=window.name,Ja=function(){},qa=window.console,Ga=qa&&qa.log&&function(a){qa.log(a)}||function(){},
Ma=function(){function a(b){return function(){Ga(b+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.J&&(W=_.J.mc());var ba=!1,X=!1,Aa=function(){if("flash"==W.rpctx)return rc.nn;if("rmr"==W.rpctx)return rc.ZA;var a="function"===typeof window.postMessage?rc.Ou:"object"===typeof window.postMessage?rc.Ou:window.ActiveXObject?rc.nn?rc.nn:rc.Oz?rc.Oz:rc.Vn:0<window.navigator.userAgent.indexOf("WebKit")?
rc.ZA:"Gecko"===window.navigator.product?rc.frameElement:rc.Vn;a||(a=Ma);return a}();x[""]=function(){Ga("Unknown RPC service: "+this.s)};x.__cb=function(a,b){var c=H[a];c&&(delete H[a],c.call(this,b))};return{config:function(a){"function"===typeof a.eB&&(Ja=a.eB)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");x[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete x[a]},NA:function(a){x[""]=a},oC:function(){delete x[""]},
rx:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=xa:"/"==a.charAt(0)&&(e=_.K.rb(window.location.href),e="/"+xa+(e?"|"+e:""));++G;c&&(H[G]=c);var g={s:b,f:e,c:c?G:0,a:Array.prototype.slice.call(arguments,3),t:E[a],l:!!C[a]},k;a:if("bidir"===Pa||"c2p"===Pa&&".."===a||"p2c"===Pa&&".."!==a){k=window.location.href;var l="?";if("query"===ca)l="#";else if("hash"===ca)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(g.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=
ma[a])||null===f(a)||(k=Aa),0===b.indexOf("legacy__")&&(k=Aa,g.s=b.substring(8),g.c=g.c?g.c:G),g.g=!0,g.r=e,k?(C[a]&&(k=rc.Vn),!1===k.call(a,e,g)&&(ma[a]=Ma,Aa.call(a,e,g))):fa[a]?fa[a].push(g):fa[a]=[g]},Wk:l,Zf:m,Wo:n,Rl:w,Rg:function(a){return E[a]},Bt:function(a){delete z[a];delete C[a];delete E[a];delete I[a];delete ma[a]},Vx:function(){return Aa.cj()},Po:function(a,b){4<a.length?Aa.KF(a,d):c.apply(null,a.concat(b))},KA:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},
0)},rb:e,Wg:function(a){var b=null,c=l(a);c?b=c:(c=f(a))?b=c.origin:b=".."==a?W.parent:window.document.getElementById(a).src;return e(b)},jc:function(){!1===Aa.jc(d,a)&&(Aa=Ma);Y?w(".."):_.fc.register("rpc",null,function(a){a=a.rpc||{};p(a);v(a)})},qw:g,JF:f,R:"__ack",Op:xa||"..",U:0,T:1,S:2}}();_.K.jc()};
_.K.config({eB:function(a){throw Error("h`"+a);}});_.Zb=_.ec;_.D("gadgets.rpc.config",_.K.config);_.D("gadgets.rpc.register",_.K.register);_.D("gadgets.rpc.unregister",_.K.unregister);_.D("gadgets.rpc.registerDefault",_.K.NA);_.D("gadgets.rpc.unregisterDefault",_.K.oC);_.D("gadgets.rpc.forceParentVerifiable",_.K.rx);_.D("gadgets.rpc.call",_.K.call);_.D("gadgets.rpc.getRelayUrl",_.K.Wk);_.D("gadgets.rpc.setRelayUrl",_.K.Zf);_.D("gadgets.rpc.setAuthToken",_.K.Wo);_.D("gadgets.rpc.setupReceiver",_.K.Rl);_.D("gadgets.rpc.getAuthToken",_.K.Rg); _.D("gadgets.rpc.removeReceiver",_.K.Bt);_.D("gadgets.rpc.getRelayChannel",_.K.Vx);_.D("gadgets.rpc.receive",_.K.Po);_.D("gadgets.rpc.receiveSameDomain",_.K.KA);_.D("gadgets.rpc.getOrigin",_.K.rb);_.D("gadgets.rpc.getTargetOrigin",_.K.Wg);

}catch(e){_._DumpException(e)}
try{
_.J=_.J||{};_.J.Bm=function(a,b,c,d){"undefined"!=typeof a.addEventListener?a.addEventListener(b,c,d):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):_.Yb("cannot attachBrowserEvent: "+b)};_.J.fM=function(a){var b=window;b.removeEventListener?b.removeEventListener("mousemove",a,!1):b.detachEvent?b.detachEvent("onmousemove",a):_.Yb("cannot removeBrowserEvent: mousemove")};

}catch(e){_._DumpException(e)}
try{
_.Gk=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=g,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,n,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),n=1518500249):(m=d^f^k,n=1859775393):60>c?(m=d&f|k&(d|f),n=2400959708):(m=d^f^k,n=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+n+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,g=a.length;e<g;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var g=63;56<=g;g--)f[g]=d&255,d>>>=8;b(f);for(g=d=0;5>g;g++)for(var l=24;0<=l;l-=8)a[d++]=e[g]>>l&255;return a}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,If:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
_.Hk=function(){function a(a){var b=_.Gk();b.update(a);return b.If()}var b=window.crypto;if(b&&"function"==typeof b.getRandomValues)return function(){var a=new window.Uint32Array(1);b.getRandomValues(a);return Number("0."+a[0])};var c=_.F("random/maxObserveMousemove");null==c&&(c=-1);var d=0,e=Math.random(),f=1,g=1E6*(window.screen.width*window.screen.width+window.screen.height),k=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;f=
f*b%g;0<c&&++d==c&&_.J.fM(k)};0!=c&&_.J.Bm(window,"mousemove",k,!1);var l=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+e);return function(){var b=f,b=b+(0,window.parseInt)(l.substr(0,20),16);l=a(l);return b/(g+Math.pow(16,20))}}();
_.D("shindig.random",_.Hk);
}catch(e){_._DumpException(e)}
try{
_.L={};_.bd={};window.iframer=_.bd;
}catch(e){_._DumpException(e)}
try{
_.L.Za=_.L.Za||{};_.L.Za.cG=function(a){try{return!!a.document}catch(b){}return!1};_.L.Za.ey=function(a){var b=a.parent;return a!=b&&_.L.Za.cG(b)?_.L.Za.ey(b):a};_.L.Za.lX=function(a){var b=a.userAgent||"";a=a.product||"";return 0!=b.indexOf("Opera")&&-1==b.indexOf("WebKit")&&"Gecko"==a&&0<b.indexOf("rv:1.")};

}catch(e){_._DumpException(e)}
try{
var ur,vr,wr,yr,zr,Ar,Fr,Gr,Hr,Ir,Kr,Lr,Mr,Or,Pr,Qr;ur=function(){_.L.cz++;return["I",_.L.cz,"_",(new Date).getTime()].join("")};vr=function(a){return a instanceof Array?a.join(","):a instanceof Object?(0,_.mc)(a):a};wr=function(){};yr=function(a){a&&a.match(xr)&&_.tb("googleapis.config/gcv",a)};zr=function(a){_.Aj.kq.bN(a)};Ar=function(a){_.Aj.kq.Ot(a)};_.Br=function(a,b){var c=b||{},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c};
_.Dr=function(a,b,c,d,e){var f=[],g;for(g in a)if(a.hasOwnProperty(g)){var k=b,l=c,m=a[g],n=d,p=Cr(g);p[k]=p[k]||{};n=_.J.Ao(n,m);m._iframe_wrapped_rpc_&&(n._iframe_wrapped_rpc_=!0);p[k][l]=n;f.push(g)}if(e)for(g in _.L.jj)_.L.jj.hasOwnProperty(g)&&f.push(g);return f.join(",")};Fr=function(a,b,c){var d={};if(a&&a._methods){a=a._methods.split(",");for(var e=0;e<a.length;e++){var f=a[e];d[f]=Er(f,b,c)}}return d};
Gr=function(a){if(a&&a.disableMultiLevelParentRelay)a=!1;else{var b;if(b=_.bd&&_.bd._open&&"inline"!=a.style&&!0!==a.inline)a=a.container,b=!(a&&("string"==typeof a&&window.document.getElementById(a)||window.document==(a.ownerDocument||a.document)));a=b}return a};Hr=function(a,b){var c={},d=b.params||{},e;for(e in a)"#"==e.charAt(0)&&(c[e.substring(1)]=a[e]),0==e.indexOf("fr-")&&(c[e.substring(3)]=a[e]),"#"==d[e]&&(c[e]=a[e]);for(var f in c)delete a["fr-"+f],delete a["#"+f],delete a[f];return c};
Ir=function(a){if(":"==a.charAt(0)){var b=_.F("iframes/"+a.substring(1));a={};_.Yl(b,a);(b=a.url)&&(a.url=_.Nm(b));a.params||(a.params={});return a}return{url:_.Nm(a)}};Kr=function(a){function b(){}b.prototype=Jr.prototype;a.prototype=new b};Lr=function(a){return _.L.Wl[a]};Mr=function(a,b){_.L.Wl[a]=b};Or=function(a){a=a||{};"auto"===a.height&&(a.height=_.Xl.Mc());var b=window&&Nr&&Nr.Ha();b?b.XA(a.width||0,a.height||0):_.bd&&_.bd._resizeMe&&_.bd._resizeMe(a)};Pr=function(a){yr(a)};
Qr=function(a){var b=_.fb(a.location.href,"urlindex");if(b=_.$a(_.jb,"fUrl",[])[b]){var c=a.location.hash,b=b+(/#/.test(b)?c.replace(/^#/,"&"):c);a.location.replace(b)}};
if(window.ToolbarApi)Nr=window.ToolbarApi,Nr.Ha=window.ToolbarApi.getInstance,Nr.prototype=window.ToolbarApi.prototype,_.h=Nr.prototype,_.h.openWindow=Nr.prototype.openWindow,_.h.Sw=Nr.prototype.closeWindow,_.h.JB=Nr.prototype.setOnCloseHandler,_.h.Kw=Nr.prototype.canClosePopup,_.h.XA=Nr.prototype.resizeWindow;else{var Nr=function(){},Rr=null;Nr.Ha=function(){!Rr&&window.external&&window.external.GTB_IsToolbar&&(Rr=new Nr);return Rr};_.h=Nr.prototype;_.h.openWindow=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.h.Sw=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.h.JB=function(a,b){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,b)};_.h.Kw=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.h.XA=function(a,b){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,b)};window.ToolbarApi=Nr;window.ToolbarApi.getInstance=Nr.Ha};
var Sr=function(){_.K.register("_noop_echo",function(){this.callback(_.L.ZH(_.L.eh[this.f]))})},Tr=function(){window.setTimeout(function(){_.K.call("..","_noop_echo",_.L.FL)},0)},Er=function(a,b,c){var d=function(d){var f=Array.prototype.slice.call(arguments,0),g=f[f.length-1];if("function"===typeof g){var k=g;f.pop()}f.unshift(b,a,k,c);_.K.call.apply(_.K,f)};d._iframe_wrapped_rpc_=!0;return d},Cr=function(a){_.L.Qo[a]||(_.L.Qo[a]={},_.K.register(a,function(b,c){var d=this.f;if(!("string"!=typeof b||
b in{}||d in{})){var e=this.callback,f=_.L.Qo[a][d],g;f&&Object.hasOwnProperty.call(f,b)?g=f[b]:Object.hasOwnProperty.call(_.L.jj,a)&&(g=_.L.jj[a]);if(g)return d=Array.prototype.slice.call(arguments,1),g._iframe_wrapped_rpc_&&e&&d.push(e),g.apply({},d)}_.Wb(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',b,'" from frame "',d,'".'].join(""));return null}));return _.L.Qo[a]};
_.L.$F=function(a,b,c){var d=Array.prototype.slice.call(arguments);_.L.Sx(function(a){a.sameOrigin&&(d.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.K.call.apply(_.K,d))})};_.L.aM=function(a,b){_.K.register(a,b)};
var xr=/^[-_.0-9A-Za-z]+$/,Vr={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},Wr={onBeforeParentOpen:"beforeparentopen"},Xr={onOpen:function(a){var b=a.Tb();a.De(b.container||b.element);return a},onClose:function(a){a.remove()}};_.L.ej=function(a){var b=_.ab();_.Yl(_.Bm,b);_.Yl(a,b);return b};
var Jr=function(a,b,c,d,e,f,g,k){this.config=Ir(a);this.openParams=this.Jl=b||{};this.params=c||{};this.methods=d;this.fp=!1;Yr(this,b.style);this.pk={};Zr(this,function(){var a;(a=this.Jl.style)&&_.L.Wl[a]?a=_.L.Wl[a]:a?(_.Yb(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=Xr;if(a){var b;if("function"===typeof a)b=a(this);else{var c={};for(b in a){var d=a[b];c[b]="function"===typeof d?_.J.Ao(a,d,this):d}b=c}for(var g in e)a=b[g],"function"===typeof a&&
$r(this,e[g],_.J.Ao(b,a))}f&&$r(this,"close",f)});this.Gg=this.ac=g;this.dt=(k||[]).slice();g&&this.dt.unshift(g.Ja())};Jr.prototype.Tb=function(){return this.Jl};Jr.prototype.Jf=function(){return this.params};Jr.prototype.zn=function(){return this.methods};Jr.prototype.Dc=function(){return this.Gg};var Yr=function(a,b){if(!a.fp){var c=b&&!_.L.Wl[b]&&_.L.Bq[b];c?(a.Aq=[],c(function(){a.fp=!0;for(var b=0,c=a.Aq.length;b<c;++b)a.Aq[b].call(a)})):a.fp=!0}},Zr=function(a,b){a.fp?b.call(a):a.Aq.push(b)};
Jr.prototype.Kc=function(a,b){Zr(this,function(){$r(this,a,b)})};var $r=function(a,b,c){a.pk[b]=a.pk[b]||[];a.pk[b].push(c)};Jr.prototype.Bi=function(a,b){Zr(this,function(){var c=this.pk[a];if(c)for(var d=0,e=c.length;d<e;++d)if(c[d]===b){c.splice(d,1);break}})};
Jr.prototype.tf=function(a,b){var c,d=this.pk[a];if(d)for(var e=Array.prototype.slice.call(arguments,1),f=0,g=d.length;f<g;++f)try{c=d[f].apply({},e)}catch(k){_.Wb(['Exception when calling callback "',a,'" with exception "',k.name,": ",k.message,'".'].join(""))}return c};
var as=function(a){return"number"==typeof a?{value:a,nr:a+"px"}:"100%"==a?{value:100,nr:"100%",yz:!0}:null},bs=function(a,b,c,d,e,f,g){Jr.call(this,a,b,c,d,Vr,e,f,g);this.id=b.id||ur();this.S=b.rpctoken&&String(b.rpctoken)||Math.round(1E9*(0,_.Hk)());this.U=Hr(this.params,this.config);this.gr={};Zr(this,function(){this.tf("open");_.Br(this.gr,this)})};Kr(bs);_.h=bs.prototype;
_.h.De=function(a,b){if(!this.config.url)return _.Wb("Cannot open iframe, empty URL."),this;var c=this.id;_.L.eh[c]=this;var d=_.Br(this.methods);d._ready=this.Ho;d._close=this.close;d._open=this.wv;d._resizeMe=this.xv;d._renderstart=this.aA;var e=this.U;this.S&&(e.rpctoken=this.S);e._methods=_.Dr(d,c,"",this,!0);this.T=a="string"===typeof a?window.document.getElementById(a):a;d={};d.id=c;if(b){d.attributes=b;var f=b.style;if("string"===typeof f){var g;if(f){g=[];for(var f=f.split(";"),k=0,l=f.length;k<
l;++k){var m=f[k];if(0!=m.length||k+1!=l)m=m.split(":"),2==m.length&&m[0].match(/^[ a-zA-Z_-]+$/)&&m[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?g.push(m.join(":")):_.Wb(['Iframe style "',f[k],'" not allowed.'].join(""))}g=g.join(";")}else g="";b.style=g}}this.Tb().allowPost&&(d.allowPost=!0);d.queryParams=this.params;d.fragmentParams=e;d.paramsSerializer=vr;this.R=_.Pm(this.config.url,a,d);e=this.R.getAttribute("data-postorigin")||this.R.src;_.L.eh[c]=this;_.K.Wo(this.id,this.S);_.K.Zf(this.id,e);return this};
_.h.Ld=function(a,b){this.gr[a]=b};_.h.Ja=function(){return this.id};_.h.mb=function(){return this.R};_.h.Bb=function(){return this.T};_.h.Ge=function(a){this.T=a};_.h.Ho=function(a){var b=Fr(a,this.id,"");this.Gg&&"function"==typeof this.methods._ready&&(a._methods=_.Dr(b,this.Gg.Ja(),this.id,this,!1),this.methods._ready(a));_.Br(a,this);_.Br(b,this);this.tf("ready",a)};_.h.aA=function(a){this.tf("renderstart",a)};_.h.close=function(a){a=this.tf("close",a);delete _.L.eh[this.id];return a};
_.h.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.h.wv=function(a){var b=Fr(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.T);if(Gr(a.openParams))new cs(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain);else{var c=new bs(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain),d=this;Zr(c,function(){var a={childId:c.Ja()},f=c.gr;f._toclose=c.close;a._methods=_.Dr(f,d.id,c.id,c,!1);b._onopen(a)})}};
_.h.xv=function(a){if(void 0===this.tf("resize",a)&&this.R){var b=as(a.width);null!=b&&(this.R.style.width=b.nr);a=as(a.height);null!=a&&(this.R.style.height=a.nr);this.R.parentElement&&(null!=b&&b.yz||null!=a&&a.yz)&&(this.R.parentElement.style.display="block")}};
var cs=function(a,b,c,d,e,f,g){Jr.call(this,a,b,c,d,Wr,e,f,g);this.url=a;this.R=null;this.vt=ur();Zr(this,function(){var a;this.tf("beforeparentopen");var b=_.Br(this.methods);b._onopen=this.AL;b._ready=this.Ho;b._onclose=this.zL;this.params._methods=_.Dr(b,"..",this.vt,this,!0);b={};for(a in this.params)b[a]=vr(this.params[a]);var c=this.config.url;if(this.Jl.hideUrlFromParent){a=window.name;var d=c,c=_.um(this.config.url,this.params,{},vr),e=b,b={};b._methods=e._methods;b["#opener"]=e["#opener"];
b["#urlindex"]=e["#urlindex"];b["#opener"]&&void 0!=e["#urlindex"]?(b["#opener"]=a+","+b["#opener"],a=d):(d=_.$a(_.jb,"fUrl",[]),e=d.length,d[e]=c,_.jb.rUrl=Qr,b["#opener"]=a,b["#urlindex"]=e,a=_.Aj.rb(_.Wa.location.href),c=_.F("iframes/relay_url_"+(0,window.encodeURIComponent)(a))||"/_/gapi/sibling/1/frame.html",a+=c);c=a}_.bd._open({url:c,openParams:this.Jl,params:b,proxyId:this.vt,openedByProxyChain:this.dt})})};Kr(cs);cs.prototype.S=function(){return this.R};
cs.prototype.AL=function(a){this.R=a.childId;var b=Fr(a,"..",this.R);_.Br(b,this);this.close=b._toclose;_.L.eh[this.R]=this;this.Gg&&this.methods._onopen&&(a._methods=_.Dr(b,this.Gg.Ja(),this.R,this,!1),this.methods._onopen(a))};cs.prototype.Ho=function(a){var b=String(this.R),c=Fr(a,"..",b);_.Br(a,this);_.Br(c,this);this.tf("ready",a);this.Gg&&this.methods._ready&&(a._methods=_.Dr(c,this.Gg.Ja(),b,this,!1),this.methods._ready(a))};
cs.prototype.zL=function(a){if(this.Gg&&this.methods._onclose)this.methods._onclose(a);else return a=this.tf("close",a),delete _.L.eh[this.R],a};
var ds=function(a,b,c,d,e,f,g){Jr.call(this,a,b,c,d,Wr,f,g);this.id=b.id||ur();this.S=e;d._close=this.close;this.onClosed=this.R;this.xC=0;Zr(this,function(){this.tf("beforeparentopen");var b=_.Br(this.methods);this.params._methods=_.Dr(b,"..",this.vt,this,!0);b={};b.queryParams=this.params;a=_.Gm(_.Xa,this.config.url,this.id,b);var c=e.openWindow(a);this.canAutoClose=function(a){a(e.Kw(c))};e.JB(c,this);this.xC=c})};Kr(ds);ds.prototype.close=function(a){a=this.tf("close",a);this.S.Sw(this.xC);return a};
ds.prototype.R=function(){this.tf("close")};
(function(){_.L.eh={};_.L.Wl={};_.L.Bq={};_.L.cz=0;_.L.Qo={};_.L.jj={};_.L.Ko=null;_.L.Jo=[];_.L.FL=function(a){var b=!1;try{if(null!=a)var e=window.parent.frames[a.id],b=e.iframer.id==a.id&&e.iframes.openedId_(_.bd.id)}catch(f){}try{_.L.Ko={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:b};for(a=0;a<_.L.Jo.length;++a)_.L.Jo[a](_.L.Ko);_.L.Jo=[]}catch(f){}};_.L.ZH=function(a){var b=a&&a.Gg,e=null;b&&(e={},e.id=b.Ja(),e.proxyChain=
a.dt);return e};Sr();if(window.parent!=window){var a=_.J.mc();a.gcv&&yr(a.gcv);var b=a.jsh;b&&zr(b);_.Br(Fr(a,"..",""),_.bd);_.Br(a,_.bd);Tr()}_.L.Ya=Lr;_.L.Yb=Mr;_.L.aN=Pr;_.L.resize=Or;_.L.xH=function(a){return _.L.Bq[a]};_.L.Qt=function(a,b){_.L.Bq[a]=b};_.L.WA=Or;_.L.mN=Pr;_.L.Sn={};_.L.Sn.get=Lr;_.L.Sn.set=Mr;_.L.OF=function(a,b){Cr(a);_.L.jj[a]=b||window[a]};_.L.SW=function(a){delete _.L.jj[a]};_.L.open=function(a,b,e,f,g,k){3==arguments.length?f={}:4==arguments.length&&"function"===typeof f&&
(g=f,f={});var l="bubble"===b.style&&Nr?Nr.Ha():null;return l?new ds(a,b,e,f,l,g,k):Gr(b)?new cs(a,b,e,f,g,k):new bs(a,b,e,f,g,k)};_.L.close=function(a,b){_.bd&&_.bd._close&&_.bd._close(a,b)};_.L.ready=function(a,b,e){2==arguments.length&&"function"===typeof b&&(e=b,b={});var f=a||{};"height"in f||(f.height=_.Xl.Mc());f._methods=_.Dr(b||{},"..","",_.bd,!0);_.bd&&_.bd._ready&&_.bd._ready(f,e)};_.L.Sx=function(a){_.L.Ko?a(_.L.Ko):_.L.Jo.push(a)};_.L.CL=function(a){return!!_.L.eh[a]};_.L.HH=function(){return["https://ssl.gstatic.com/gb/js/",
_.F("googleapis.config/gcv")].join("")};_.L.FA=function(a){var b={mouseover:1,mouseout:1};if(_.bd._event)for(var e=0;e<a.length;e++){var f=a[e];f in b&&_.J.Bm(window.document,f,function(a){_.bd._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.L.eN=zr;_.L.Ot=Ar;_.L.Fz=wr;_.L.iz=_.bd})();
_.D("iframes.allow",_.L.OF);_.D("iframes.callSiblingOpener",_.L.$F);_.D("iframes.registerForOpenedSibling",_.L.aM);_.D("iframes.close",_.L.close);_.D("iframes.getGoogleConnectJsUri",_.L.HH);_.D("iframes.getHandler",_.L.Ya);_.D("iframes.getDeferredHandler",_.L.xH);_.D("iframes.getParentInfo",_.L.Sx);_.D("iframes.iframer",_.L.iz);_.D("iframes.open",_.L.open);_.D("iframes.openedId_",_.L.CL);_.D("iframes.propagate",_.L.FA);_.D("iframes.ready",_.L.ready);_.D("iframes.resize",_.L.resize);
_.D("iframes.setGoogleConnectJsVersion",_.L.aN);_.D("iframes.setBootstrapHint",_.L.Ot);_.D("iframes.setJsHint",_.L.eN);_.D("iframes.setHandler",_.L.Yb);_.D("iframes.setDeferredHandler",_.L.Qt);_.D("IframeBase",Jr);_.D("IframeBase.prototype.addCallback",Jr.prototype.Kc);_.D("IframeBase.prototype.getMethods",Jr.prototype.zn);_.D("IframeBase.prototype.getOpenerIframe",Jr.prototype.Dc);_.D("IframeBase.prototype.getOpenParams",Jr.prototype.Tb);_.D("IframeBase.prototype.getParams",Jr.prototype.Jf);
_.D("IframeBase.prototype.removeCallback",Jr.prototype.Bi);_.D("Iframe",bs);_.D("Iframe.prototype.close",bs.prototype.close);_.D("Iframe.prototype.exposeMethod",bs.prototype.Ld);_.D("Iframe.prototype.getId",bs.prototype.Ja);_.D("Iframe.prototype.getIframeEl",bs.prototype.mb);_.D("Iframe.prototype.getSiteEl",bs.prototype.Bb);_.D("Iframe.prototype.openInto",bs.prototype.De);_.D("Iframe.prototype.remove",bs.prototype.remove);_.D("Iframe.prototype.setSiteEl",bs.prototype.Ge);
_.D("Iframe.prototype.addCallback",bs.prototype.Kc);_.D("Iframe.prototype.getMethods",bs.prototype.zn);_.D("Iframe.prototype.getOpenerIframe",bs.prototype.Dc);_.D("Iframe.prototype.getOpenParams",bs.prototype.Tb);_.D("Iframe.prototype.getParams",bs.prototype.Jf);_.D("Iframe.prototype.removeCallback",bs.prototype.Bi);_.D("IframeProxy",cs);_.D("IframeProxy.prototype.getTargetIframeId",cs.prototype.S);_.D("IframeProxy.prototype.addCallback",cs.prototype.Kc);_.D("IframeProxy.prototype.getMethods",cs.prototype.zn);
_.D("IframeProxy.prototype.getOpenerIframe",cs.prototype.Dc);_.D("IframeProxy.prototype.getOpenParams",cs.prototype.Tb);_.D("IframeProxy.prototype.getParams",cs.prototype.Jf);_.D("IframeProxy.prototype.removeCallback",cs.prototype.Bi);_.D("IframeWindow",ds);_.D("IframeWindow.prototype.close",ds.prototype.close);_.D("IframeWindow.prototype.onClosed",ds.prototype.R);_.D("iframes.util.getTopMostAccessibleWindow",_.L.Za.ey);_.D("iframes.handlers.get",_.L.Sn.get);_.D("iframes.handlers.set",_.L.Sn.set); _.D("iframes.resizeMe",_.L.WA);_.D("iframes.setVersionOverride",_.L.mN);
Jr.prototype.send=function(a,b,c){_.L.kB(this,a,b,c)};_.bd.send=function(a,b,c){_.L.kB(_.bd,a,b,c)};Jr.prototype.register=function(a,b){var c=this;c.Kc(a,function(a){b.call(c,a)})};_.L.kB=function(a,b,c,d){var e=[];void 0!==c&&e.push(c);d&&e.push(function(a){d.call(this,[a])});a[b]&&a[b].apply(a,e)};_.L.Sj=function(){return!0};_.D("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.L.Sj);_.D("IframeBase.prototype.send",Jr.prototype.send);_.D("IframeBase.prototype.register",Jr.prototype.register);
_.D("Iframe.prototype.send",bs.prototype.send);_.D("Iframe.prototype.register",bs.prototype.register);_.D("IframeProxy.prototype.send",cs.prototype.send);_.D("IframeProxy.prototype.register",cs.prototype.register);_.D("IframeWindow.prototype.send",ds.prototype.send);_.D("IframeWindow.prototype.register",ds.prototype.register);_.D("iframes.iframer.send",_.L.iz.send);

}catch(e){_._DumpException(e)}
try{
_.J=_.J||{};
(function(){function a(b){var c="";if(3==b.nodeType||4==b.nodeType)c=b.nodeValue;else if(b.innerText)c=b.innerText;else if(b.innerHTML)c=b.innerHTML;else if(b.firstChild){c=[];for(b=b.firstChild;b;b=b.nextSibling)c.push(a(b));c=c.join("")}return c}_.J.createElement=function(a){var c;if(!window.document.body||window.document.body.namespaceURI)try{c=window.document.createElementNS("http://www.w3.org/1999/xhtml",a)}catch(d){}return c||window.document.createElement(a)};_.J.xq=function(a){var c=_.J.createElement("iframe");
try{var d=["<","iframe"],e=a||{},f;for(f in e)e.hasOwnProperty(f)&&(d.push(" "),d.push(f),d.push('="'),d.push(_.J.fn(e[f])),d.push('"'));d.push("></");d.push("iframe");d.push(">");var g=_.J.createElement(d.join(""));g&&(!c||g.tagName==c.tagName&&g.namespaceURI==c.namespaceURI)&&(c=g)}catch(l){}d=c;a=a||{};for(var k in a)a.hasOwnProperty(k)&&(d[k]=a[k]);return c};_.J.un=function(){if(window.document.body)return window.document.body;try{var a=window.document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml", "body");if(a&&1==a.length)return a[0]}catch(c){}return window.document.documentElement||window.document};_.J.bX=function(b){return a(b)}})();

}catch(e){_._DumpException(e)}
try{
_.Qj=function(){return Math.floor((new Date).getTime()/1E3)};var Sj,Tj;_.Rj=function(a,b){this.R=a;var c=b||{};this.U=Number(c.maxAge)||0;this.S=c.domain;this.T=c.path;this.W=!!c.secure};Sj=/^[-+/_=.:|%&a-zA-Z0-9@]*$/;Tj=/^[A-Z_][A-Z0-9_]{0,63}$/;_.Rj.prototype.read=function(){for(var a=this.R+"=",b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c];if(0==d.indexOf(a))return d.substr(a.length)}};
_.Rj.prototype.write=function(a,b){if(!Tj.test(this.R))throw"Invalid cookie name";if(!Sj.test(a))throw"Invalid cookie value";var c=this.R+"="+a;this.S&&(c+=";domain="+this.S);this.T&&(c+=";path="+this.T);var d="number"===typeof b?b:this.U;if(0<=d){var e=new Date;e.setSeconds(e.getSeconds()+d);c+=";expires="+e.toUTCString()}this.W&&(c+=";secure");window.document.cookie=c;return!0};_.Rj.prototype.clear=function(){this.write("",0)}; _.Rj.iterate=function(a){for(var b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c].split("="),e=d.shift();a(e,d.join("="))}};
var Vj;_.Uj=function(a){this.R=a};Vj={};_.Uj.prototype.read=function(){if(Vj.hasOwnProperty(this.R))return Vj[this.R]};_.Uj.prototype.write=function(a){Vj[this.R]=a;return!0};_.Uj.prototype.clear=function(){delete Vj[this.R]};_.Uj.iterate=function(a){for(var b in Vj)Vj.hasOwnProperty(b)&&a(b,Vj[b])};
var Wj,Xj;Wj=function(){this.R=null;this.key=function(){return null};this.getItem=function(){return this.R};this.setItem=function(a,b){this.R=b;this.length=1};this.removeItem=function(){this.clear()};this.clear=function(){this.R=null;this.length=0};this.length=0};Xj=function(a){try{var b=a||window.sessionStorage;if(!b)return!1;b.setItem("gapi.sessionStorageTest","gapi.sessionStorageTest"+b.length);b.removeItem("gapi.sessionStorageTest");return!0}catch(c){return!1}};
_.Yj=function(a,b){this.R=a;this.S=Xj(b)?b||window.sessionStorage:new Wj};_.Yj.prototype.read=function(){return this.S.getItem(this.R)};_.Yj.prototype.write=function(a){try{this.S.setItem(this.R,a)}catch(b){return!1}return!0};_.Yj.prototype.clear=function(){this.S.removeItem(this.R)};_.Yj.iterate=function(a){if(Xj())for(var b=0,c=window.sessionStorage.length;b<c;++b){var d=window.sessionStorage.key(b);a(d,window.sessionStorage[d])}};
for(var Zj=0;64>Zj;++Zj);_.ak="https:"===window.location.protocol;_.bk=_.ak||"http:"===window.location.protocol?_.Rj:_.Uj;_.ck=function(a){var b=a.substr(1),c="",d=window.location.hostname;if(""!==b){c=(0,window.parseInt)(b,10);if((0,window.isNaN)(c))return null;b=d.split(".");if(b.length<c-1)return null;b.length==c-1&&(d="."+d)}else d="";return{uc:"S"==a.charAt(0),domain:d,pe:c}};
var dk;dk=[".APPS.GOOGLEUSERCONTENT.COM","@DEVELOPER.GSERVICEACCOUNT.COM"];_.ek=function(a){a=a.toUpperCase();for(var b=0,c=dk.length;b<c;++b){var d=a.split(dk[b]);2==d.length&&""===d[1]&&(a=d[0])}a=a.replace(/-/g,"_").toUpperCase();40<a.length&&(b=new _.Pj,b.Du(a),a=b.If().toUpperCase());return a};
_.fk=function(a){if(0!==a.indexOf("GCSC"))return null;var b={vd:!1};a=a.substr(4);if(!a)return b;var c=a.charAt(0);a=a.substr(1);var d=a.lastIndexOf("_");if(-1==d)return b;var e=_.ck(a.substr(d+1));if(null==e)return b;a=a.substring(0,d);if("_"!==a.charAt(0))return b;d="E"===c&&e.uc;return!d&&("U"!==c||e.uc)||d&&!_.ak?b:{vd:!0,uc:d,Pw:a.substr(1),domain:e.domain,pe:e.pe}};
var gk,hk,lk,mk,pk;gk=_.ab();hk=_.ab();_.ik=_.ab();_.jk=_.ab();_.kk=null;lk="state code cookie_policy g_user_cookie_policy authuser prompt g-oauth-window status".split(" ");mk=function(a){this.S=a;this.R=null};mk.prototype.write=function(a){var b=_.ab(),c=_.ab(),d;for(d in a)_.bb(a,d)&&(c[d]=a[d],b[d]=a[d]);d=0;for(var e=lk.length;d<e;++d)delete c[lk[d]];a=String(a.authuser||0);d=_.ab();d[a]=_.J.mc("#"+_.nk(c));this.S.write((0,_.mc)(d));this.R=b};mk.prototype.read=function(){return this.R};
mk.prototype.clear=function(){this.S.clear();this.R=_.ab()};
_.ok=function(a){if(!a)return null;"single_host_origin"!==a&&(a=_.K.rb(a));var b=window.location.hostname,c=b,d=_.ak;if("single_host_origin"!==a){c=a.split("://");if(2==c.length)d="https"===c.shift();else return _.dc("WARNING invalid cookie_policy: "+a),null;c=c[0]}if(-1!==c.indexOf(":"))c=b="";else{a="."+c;if(b.lastIndexOf(a)!==b.length-a.length)return _.dc("Invalid cookie_policy domain: "+c),null;c=a;b=c.split(".").length-1}return{domain:c,uc:d,pe:b}};
pk=function(a){if(!a)return null;var b=a.client_id;if(!b)return null;b=_.ek(b);a=_.ok(a.cookie_policy);return a?!_.ak&&a.uc?(_.dc("WARNING: https cookie_policy set for http domain"),null):["GCSC",a.uc?"E":"U","_",b,"_",a.uc?"S":"H",a.pe].join(""):null};_.qk=function(a){return a?{domain:a.domain,path:"/",secure:a.uc}:null};_.rk=function(a){var b=gk[a];b||(b=new mk(new _.Uj(a)),gk[a]=b);return{Xe:b,key:a}};
_.sk=function(a,b){var c=b?hk:gk,d=b?_.bk:_.Yj,e=a&&pk(a),f=!!e;a&&!a.g_user_cookie_policy&&(d=_.Uj,e="token");if(!e)if(!b&&_.kk)e=_.kk;else return null;var g=c[e];if(!g){g=_.fk(e);if(!("token"===e||g&&g.vd))return null;g=new d(e,_.qk(g));b||(g=new mk(g))}c[e]=g;return{Xe:g,key:e,gH:f}};
_.tk=function(a,b,c){a=a&&"token"!==a?_.rk(a):_.sk();if(!a)return null;if(c){c=a.Xe;_.ab();var d=c.S.read();c=null;try{c=(0,_.nc)(d)}catch(e){}0==c&&(c=null);d=_.Hj()||"0";d=String(d);c=c&&c[d]}else c=a.Xe.read();c&&c.expires_at&&_.Qj()>c.expires_at&&(a.Xe.clear(),c=null);c&&c.error&&!b&&(c=null);return c};
_.nk=function(a){var b="";if(!a)return b;for(var c in a)if({}.hasOwnProperty.call(a,c)){var d;d=a[c];if(null!=d){var e=[(0,window.encodeURIComponent)(c),"="];if(d instanceof Array){for(var f=[],g=0;g<d.length;g++)f.push((0,window.encodeURIComponent)(d[g]));e.push(f.join("+"))}else e.push((0,window.encodeURIComponent)(d));d=e.join("")}else d="";d&&(b&&(b+="&"),b+=d)}return b};_.Yj.iterate(function(a){var b=_.fk(a);b&&b.vd&&(gk[a]=new mk(new _.Yj(a)))}); _.bk.iterate(function(a){gk[a]&&(hk[a]=new _.bk(a,_.qk(_.fk(a))))});

}catch(e){_._DumpException(e)}
try{
_.Ej=window.googleapis&&window.googleapis.server||{};
}catch(e){_._DumpException(e)}
try{
_.uk=function(){var a=/\s*;\s*/;return{get:function(b,c){for(var d=b+"=",e=(window.document.cookie||"").split(a),f=0,g;g=e[f];++f)if(0==g.indexOf(d))return g.substr(d.length);return c}}}();
}catch(e){_._DumpException(e)}
try{
_.cd=function(a){var b=_.Fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.dd=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ed=function(a){return"number"==typeof a};_.fd=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.gd=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.hd=2147483648*Math.random()|0;
}catch(e){_._DumpException(e)}
try{
var ld;_.id=function(a){return/^[\s\xa0]*$/.test(a)};_.jd=function(a,b){return 0==a.lastIndexOf(b,0)};_.kd=function(a){return null==a?"":String(a)};ld=0;_.md=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};_.nd=function(a){return a[_.Ia]||(a[_.Ia]=++ld)};_.od=function(a){return"function"==_.Fa(a)};
_.pd=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.qd=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.rd=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.sd=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e};_.td=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.vd=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.wd=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.xd=function(a,b){return 0<=(0,_.pd)(a,b)};
_.zd=function(a,b){var c=(0,_.pd)(a,b),d;(d=0<=c)&&_.yd(a,c);return d};_.yd=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Ad=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.cd(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};

}catch(e){_._DumpException(e)}
try{
var wk,xk;_.vk=function(a){this.R=a||{cookie:""}};wk=/\s*;\s*/;_.h=_.vk.prototype;_.h.isEnabled=function(){return window.navigator.cookieEnabled};_.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("D`"+a);if(/[;\r\n]/.test(b))throw Error("E`"+b);_.Da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.Qa)()+1E3*c)).toUTCString();this.R.cookie=a+"="+b+e+d+c+f};
_.h.get=function(a,b){for(var c=a+"=",d=(this.R.cookie||"").split(wk),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=_.Da(this.get(a));this.set(a,"",0,b,c);return d};_.h.Nd=function(){return xk(this).keys};_.h.Nc=function(){return xk(this).values};_.h.isEmpty=function(){return!this.R.cookie};_.h.Nb=function(){return this.R.cookie?(this.R.cookie||"").split(wk).length:0};
_.h.Jh=function(a){for(var b=xk(this).values,c=0;c<b.length;c++)if(b[c]==a)return!0;return!1};_.h.clear=function(){for(var a=xk(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};xk=function(a){a=(a.R.cookie||"").split(wk);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};_.yk=new _.vk("undefined"==typeof window.document?null:window.document);_.yk.S=3950;

}catch(e){_._DumpException(e)}
try{
var zk=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(a){for(var b=g,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,n,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),n=1518500249):(m=d^f^k,n=1859775393):60>c?(m=d&f|k&(d|f),n=2400959708):(m=d^f^k,n=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+n+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,g=a.length;e<g;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64;for(;d<c;)if(f[m++]=a[d++],n++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,n+=64}function d(){var a=[],
d=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var g=63;56<=g;g--)f[g]=d&255,d>>>=8;b(f);for(g=d=0;5>g;g++)for(var l=24;0<=l;l-=8)a[d++]=e[g]>>l&255;return a}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,If:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
var Bk=function(a,b,c){var d=[],e=[];if(1==(_.Ha(c)?2:1))return e=[b,a],(0,_.rd)(d,function(a){e.push(a)}),Ak(e.join(" "));var f=[],g=[];(0,_.rd)(c,function(a){g.push(a.key);f.push(a.value)});c=Math.floor((new Date).getTime()/1E3);e=0==f.length?[c,b,a]:[f.join(":"),c,b,a];(0,_.rd)(d,function(a){e.push(a)});a=Ak(e.join(" "));a=[c,a];0==g.length||a.push(g.join(""));return a.join("_")},Ak=function(a){var b=zk();b.update(a);return b.If().toLowerCase()};
var Dk;_.Ck=function(a){var b={SAPISIDHASH:!0,APISIDHASH:!0};return a&&(a.OriginToken||a.Authorization&&b[String(a.Authorization).split(" ")[0]])?!0:!1};Dk=function(){var a=_.r.__OVERRIDE_SID;null==a&&(a=(new _.vk(window.document)).get("SID"));return!!a};
_.Ek=function(a){var b=_.Dj(String(_.r.location.href));if(Dk()){var c=0==b.indexOf("https:")||0==b.indexOf("chrome-extension:"),b=c?_.r.__SAPISID:_.r.__APISID;null==b&&(b=(new _.vk(window.document)).get(c?"SAPISID":"APISID"));if(b){var c=c?"SAPISIDHASH":"APISIDHASH",d=String(_.r.location.href);return d&&b&&c?[c,Bk(_.Dj(d),b,a||null)].join(" "):null}}return null};
_.Fk={PJ:_.Ck,FK:Dk,aI:function(){var a=null;Dk()&&(a=window.__PVT,null==a&&(a=_.uk.get("BEAT")));return a},qr:_.Ek};
}catch(e){_._DumpException(e)}
try{
_.Vh=function(a){return(0,window.encodeURIComponent)(String(a))};_.Wh=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.Xh=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};_.Yh=function(a,b,c){if(_.Ha(b))for(var d=0;d<b.length;d++)_.Yh(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",_.Vh(b))}; _.Zh=function(a,b){for(var c in b)_.Yh(c,b[c],a);return a};

}catch(e){_._DumpException(e)}
try{
var Ik;Ik=function(a,b){var c=_.J.xq({id:a,name:a});c.style.width="1px";c.style.height="1px";c.style.position="absolute";c.style.top="-100px";var d;if(window.navigator){d=window.navigator.userAgent||"";var e=window.navigator.product||"";d=0!=d.indexOf("Opera")&&-1==d.indexOf("WebKit")&&"Gecko"==e&&0<d.indexOf("rv:1.")}else d=!1;c.src=d?"about:blank":b;c.tabIndex="-1";window.document.body.appendChild(c);d&&(c.src=b);return c};
_.Jk=function(){function a(){return!!g("auth/useFirstPartyAuthV2")}function b(a,b,c,d){var e=g("proxy");if(c||!e)var e=g("root"),f=g("root-1p")||e,e=e||"https://content.googleapis.com",f=f||"https://clients6.google.com",k=g("xd3")||"/static/proxy.html",e=(c||String(b?f:e))+k;e=String(e);(b=_.J.mc().jsh||_.Aj.kq.Kx())&&(e+=(0<=e.indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(b));g("push")&&(e+=(0<=e.indexOf("?")?"&":"?")+"p=1");e+="#parent="+(0,window.encodeURIComponent)(null!=d?String(d):
_.Aj.rb(window.document.location.href));return e+("&rpctoken="+a)}function c(a,b,c,d){var g=e(c,d);l[g]||(c=Ik(g,b),_.K.register("ready:"+a,function(){_.K.unregister("ready:"+a);if(!m[g]){m[g]=!0;var b=n[g];n[g]=[];for(var c=0,d=b.length;c<d;++c){var e=b[c];f(e.Ei,e.mM,e.Yc)}}}),_.K.Rl(g,b),l[g]=c)}function d(a,d){var e=String(2147483647*(0,_.Hk)()|0),f=b(e,a,d);_.pc(function(){c(e,f,a,d)})}function e(a,c){var d=b("",a,c,""),e=k[d];e||(e=_.Gk(),e.update(d),e=e.If().toLowerCase(),e+=Math.random(),
k[d]=e);return"apiproxy"+e}function f(a,b,c){var f=void 0,g=!1;if("makeHttpRequests"!==a)throw'only "makeHttpRequests" RPCs are implemented';var k=function(a){if(a){if("undefined"!=typeof f&&"undefined"!=typeof a.root&&f!=a.root)throw"all requests in a batch must have the same root URL";f=a.root||f;g=_.Fk.PJ(a.headers)}};if(b)for(var C=0,E=b.length;C<E;++C){var G=b[C];G&&k(G.params)}var H=e(g,f);l[H]||d(g,f);m[H]?_.K.call(H,a,function(a){if(this.f==H&&this.t==_.K.Rg(this.f)&&this.origin==_.K.Wg(this.f)){var b=
(0,_.nc)(a);c(b,a)}},b):(n[H]||(n[H]=[]),n[H].push({Ei:a,mM:b,Yc:c}))}function g(a){return _.F("googleapis.config/"+a)}var k={},l={},m={},n={};return{zw:function(b,c,d){var e=d||"auto";b=b||{};if("none"==e)return b;c=c||window.location.href;d=b.Authorization;var f=b.OriginToken;if(!d&&!f){f=_.tk(void 0,void 0);!f&&window.gapi.auth2&&"function"==typeof window.gapi.auth2._gt&&(f=window.gapi.auth2._gt());f&&f.access_token&&("oauth2"==e||"auto"==e)&&(d=String(f.token_type||"Bearer")+" "+f.access_token);
if(f=!d)f=(!!g("auth/useFirstPartyAuth")||"1p"==e)&&"oauth2"!=e;if(f&&_.Fk.FK()){if(a()){d=g("primaryEmail");var e=g("appDomain"),f=g("fogId"),k=[];d&&k.push({key:"e",value:d});e&&k.push({key:"a",value:e});f&&k.push({key:"u",value:f});d=_.Fk.qr(k)}else d=_.Fk.qr();d&&(c=_.google.Ir(c),c=b["X-Goog-AuthUser"]||c,_.id(_.kd(c))&&(!a()||a()&&_.id(_.kd(g("primaryEmail")))&&_.id(_.kd(g("appDomain")))&&_.id(_.kd(g("fogId"))))&&(c="0"),_.id(_.kd(c))||(b["X-Goog-AuthUser"]=c))}d?b.Authorization=d:!1!==g("auth/useOriginToken")&& (f=_.Fk.aI())&&(b.OriginToken=f)}return b},Ej:f}}();

}catch(e){_._DumpException(e)}
try{
var Kk=["appVersion","platform","userAgent"],Lk=function(a){if(a&&window.navigator){for(var b=[],c=0;c<Kk.length;c++){var d=window.navigator[Kk[c]];d&&b.push((0,window.encodeURIComponent)(Kk[c])+"="+(0,window.encodeURIComponent)(d))}a["X-ClientDetails"]=b.join("&")}},Mk=function(a){return{execute:function(b){var c={};if(a.headers)for(var d in a.headers)Object.prototype.hasOwnProperty.call(a.headers,d)&&(c[d]=a.headers[d]);c=_.Jk.zw(c);Lk(c);var e={},f=a.urlParams;if(f)for(d in f)Object.hasOwnProperty.call(f,
d)&&(e[d]=f[d]);d=_.F("googleapis.config/developerKey");(d=_.F("client/apiKey",d))&&!e.key&&(e.key=String(d));(d=_.F("client/trace"))&&!e.trace&&(e.trace=String(d));_.Jk.Ej("makeHttpRequests",[{key:"googleapisRequest",params:{id:"googleapisRequest",key:"googleapisRequest",clientVersion:"1.0.0-alpha",httpMethod:a.httpMethod||"GET",root:a.root,url:a.url,urlParams:e,headers:c,body:a.body}}],function(a){return function(b){a(b.googleapisRequest.data)}}(b))}}},Nk=function(a,b){return function(c){var d=
{};c=c.body;var e=(0,_.nc)(c),f={};if(e&&e.length)for(var g=0,k=e.length;g<k;++g){var l=e[g];f[l.id]=l}g=0;for(k=b.length;g<k;++g)l=b[g].id,d[l]=e&&e.length?f[l]:e;a(d,c)}},Ok=function(a,b){a.transport={name:"googleapis",execute:function(b,d){for(var e=[],f=0,g=b.length;f<g;++f){var k=b[f],l=k.method,m=String(l).split(".")[0],m=_.F("googleapis.config/versions/"+l)||_.F("googleapis.config/versions/"+m)||"v1";e.push({jsonrpc:"2.0",id:k.id,method:l,apiVersion:String(m),params:k.params})}f=Mk({httpMethod:"POST",
root:a.transport.root,url:"/rpc?pp=0",headers:{"Content-Type":"application/json"},body:e});f.execute.call(f,Nk(d,e))},root:b}},Pk=function(a){var b=this.method,c=this.transport;c.execute.call(c,[{method:b,id:b,params:this.rpc}],function(c){c=c[b];c.error||(c=c.data||c.result);a(c)})},Qk=function(a,b,c){a={method:a,rpc:b||{}};Ok(a,c);a.execute=Pk;return a},Rk=function(a,b){for(var c=a.split("."),d=function(c){c=c||{};c.groupId=c.groupId||"@self";c.userId=c.userId||"@viewer";return Qk(a,c,b)},e=_.r,
f=0,g=c.length;f<g;++f){var k=e[c[f]]||{};f+1==g&&(k=d);e=e[c[f]]=k}if(1<c.length&&"googleapis"!=c[0])for(c[0]="googleapis","delete"==c[c.length-1]&&(c[c.length-1]="remove"),e=_.r,f=0,g=c.length;f<g;++f)k=e[c[f]]||{},f+1==g&&(k=d),e=e[c[f]]=k},Sk;for(Sk in _.F("googleapis.config/methods"))Rk(Sk);
_.D("googleapis.newRequest",function(a,b,c){return Qk(a,b,c)});_.D("googleapis.newHttpRequest",function(a){return Mk(a)});_.D("googleapis.register",function(a,b){Rk(a,b)});_.D("googleapis.setUrlParameter",function(a,b){if("trace"!==a)throw Error("F");_.tb("client/trace",b)});_.D("googleapis.setDeveloperKey",function(a){_.tb("googleapis.config/developerKey",a);_.tb("client/apiKey",a)});_.D("googleapis.setVersions",function(a){_.tb("googleapis.config/versions",a)});

}catch(e){_._DumpException(e)}
})(this._);
// Google Inc.
